apiVersion : actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: BASEBUILD
spec:
  template:
    metadata:
      labels:
        app: BASEBUILD
    spec:
      organization: eldarrin
      image: "eldarrin/gitrunners/BASEBUILD:LATESTTAG"
      dockerEnabled: false
      imagePullSecrets:
        - name: eldarrin
      labels:
        - buildah
      env:
        - name: DISABLE_RUNNER_UPDATE
          value: "true"