apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: BASEBUILD-runner-deployment-autoscaler
spec:
  scaleTargetRef:
    name: BASEBUILD
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: '0.5'     # The percentage of busy runners at which the number of desired runners are re-evaluated to scale up
      scaleDownThreshold: '0.3'   # The percentage of busy runners at which the number of desired runners are re-evaluated to scale down
      scaleUpFactor: '2'          # The scale up multiplier factor applied to desired count
      scaleDownFactor: '0.7'      # The scale down multiplier factor applied to desired count