apiVersion: v1
kind: Service
metadata:
  labels:
    expose: "true"
    app: dind-swarm
  name: dind-swarm
spec:
  ports:
    - name: docker
      port: 2375
      protocol: TCP
      targetPort: 2375
  selector:
    app: dind-swarm
  type: ClusterIP
