name: Git Runner Image Build

on:
  push:
    branches: [ develop ]

env:
  TAG: "latest"

jobs:
  ci-runner:
    strategy:
      matrix:
        runner-name:  ["main"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: build and push the ${{ matrix.runner-name }} image
        run: |
          cd build
          docker build -t eldarrin/git-main:latest .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          docker push eldarrin/git-main:latest