name: Full Image Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  TAG: ${{ github.run_id }}


jobs:
  pre-build:
    strategy:
      matrix:
        runner-name: ["main", "dind-swarm"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: build and push the base ${{ matrix.runner-name }} image
        run: |
          cd bases/${{ matrix.runner-name }}
          printenv
          sed -i "s/LATESTTAG/${{ env.TAG }}/g" Dockerfile
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          docker build -t eldarrin/base-${{ matrix.runner-name }}:${{ env.TAG }} .
          docker push eldarrin/base-${{ matrix.runner-name }}:${{ env.TAG }}
          
  primary-build:
    needs: pre-build
    strategy:
      matrix:
        runner-name: ["buildah", "kube", "docker"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: build and push the base ${{ matrix.runner-name }} image
        run: |
          cd bases/${{ matrix.runner-name }}
          sed -i "s/LATESTTAG/${{ env.TAG }}/g" Dockerfile
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          docker build -t eldarrin/base-${{ matrix.runner-name }}:${{ env.TAG }} .
          docker push eldarrin/base-${{ matrix.runner-name }}:${{ env.TAG }}
          
  secondary-build:
    needs: primary-build
    strategy:
      matrix:
        runner-name: ["maven"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: build and push the base ${{ matrix.runner-name }} image
        run: |
          cd bases/${{ matrix.runner-name }}
          sed -i "s/LATESTTAG/${{ env.TAG }}/g" Dockerfile
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          docker build -t eldarrin/base-${{ matrix.runner-name }}:${{ env.TAG }} .
          docker push eldarrin/base-${{ matrix.runner-name }}:${{ env.TAG }}
          
  ci-bases:
    needs: pre-build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: create and push manifests
        run: |
          cd dind-swarm
          sed -i "s/LATESTTAG/${{ env.TAG }}/g" dind-deployment.yaml
          # push dind-deployment.yaml somewhere
          
  ci-runner:
    needs: secondary-build
    strategy:
      matrix:
        runner-name:  ["main", "buildah", "kube", "maven", "docker"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: build and push the ${{ matrix.runner-name }} image
        run: |
          cd gitrunners
          sed -i "s/BASEBUILD/${{ matrix.runner-name }}/g" Dockerfile
          sed -i "s/LATESTTAG/${{ env.TAG }}/g" Dockerfile
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          docker build -t eldarrin/gitrunner-${{ matrix.runner-name }}:${{ env.TAG }} .
          docker push eldarrin/gitrunner-${{ matrix.runner-name }}:${{ env.TAG }}
