name: Test Runner

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

env:
  TAG: "latest"

jobs:
  ci-runner:
    strategy:
      matrix:
        runner-name:  ["main"]

    runs-on: "main"

    steps:
      - name: echoer
        run: |
          echo I am a thing
