name: Test Runner - new

on:
  workflow_dispatch:

env:
  TAG: "latest"

jobs:
  test:
    runs-on: ["self-hosted"]
    strategy:
      matrix:
        scene: [1, 2]

    steps:
      - name: echoer
        run: |
          echo I am a thing
          echo I have finished being a thing
